integration: rspec
matcher:
  subjects:
    - Fixably*
  ignore:
    - Fixably::ApplicationResource#encode
    - Fixably::ApplicationResource.expand_associations
    - Fixably::Actions*
    - Fixably::ActiveResource::PaginatedCollection#paginated_each
    - Fixably::ActiveResource::PaginatedCollection#paginated_map
    - Fixably::ArgumentParameterisation#associations
    - Fixably::ArgumentParameterisation#expand_association
    - Fixably::ArgumentParameterisation#expand_associations
    - Fixably::ArgumentParameterisation#stringify_array_values
    - Fixably::Customer#encode
    - Fixably::Encoding#encode
    - Fixably::Encoding#remove_has_many_associations
    - Fixably::Encoding#remove_unallowed_parameters
    - Fixably::LoadFromResponse#load
    - Fixably::ResourceLazyLoader*
mutation_timeout: 5.0
requires:
  - fixably
